extends:
  import: classic
  file: maven/pipeline.yaml
pipelines:
  pullRequest:
    build:
      steps:
      - sh: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.15.0/skaffold-linux-amd64 && chmod +x skaffold && cp skaffold /usr/local/bin && /usr/local/bin/skaffold version
        name: skaffold-version
      - sh: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.15.0/skaffold-linux-amd64 && chmod +x skaffold &&  export VERSION=$PREVIEW_VERSION && ./skaffold build -f skaffold.yaml
        name: container-build
    postBuild:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
        name: post-build
    promote:
      steps:
      - dir: charts/preview
        steps:
        - sh: make preview
          name: make-preview
        - sh: jx preview --app $APP_NAME --dir ../..
          name: jx-preview

  release:
    setVersion:
      replace: true
      steps:
        - sh: echo \$(jx-release-version) > VERSION
          name: next-version
        - sh: mvn versions:set -DnewVersion=\$(cat VERSION)
          name: set-version
        - sh: export VERSION=`cat VERSION` && jx step tag -d charts/user-service -v $VERSION -r 736480167897.dkr.ecr.eu-central-1.amazonaws.com/1card/jux-microservices/user-service --no-apply && jx step tag -d charts/merchant-service -v $VERSION -r 736480167897.dkr.ecr.eu-central-1.amazonaws.com/1card/jux-microservices/merchant-service
          name: tag-version
    build:
      steps:
      - sh: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.15.0/skaffold-linux-amd64 && chmod +x skaffold && cp skaffold /usr/local/bin && /usr/local/bin/skaffold version
        name: skaffold-version
      - sh: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.15.0/skaffold-linux-amd64 && chmod +x skaffold && pwd && ./skaffold build -f skaffold.yaml
        name: container-build
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
        name: post-build
    promote:
      steps:
      - dir: charts/user-service
        steps:
        - sh: jx step changelog -t . --version v\$(cat ../../VERSION)
          name: changelog-userservice
        - comment: version the helm chart
          sh: jx step helm version --version \$(cat ../../VERSION)
          name: helm-version-userservice
        - comment: release the helm chart
          sh: export CHART_REPOSITORY=https://chartmuseum-jx.juxapp.co.uk && curl -fsSL -o /tmp/helm-v2.17.0-linux-amd64.tar.gz https://get.helm.sh/helm-v2.17.0-linux-amd64.tar.gz && tar -xvzf /tmp/helm-v2.17.0-linux-amd64.tar.gz --strip-components=1 -C /usr/bin/ linux-amd64/helm && helm version --client && helm init --client-only && jx step helm release && helm repo update
          name: helm-release-userservice
        - comment: promote to development Environment
          sh: helm init --client-only --stable-repo-url https://charts.helm.sh/stable && jx promote -r jux-jx-charts --verbose --env development --timeout 1h --version \$(cat ../../VERSION)
          name: jx-promote-userservice-development
        - comment: promote to production Environment
          sh: helm init --client-only --stable-repo-url https://charts.helm.sh/stable && jx promote -r jux-jx-charts --verbose --no-merge --env prod --timeout 24h --version \$(cat ../../VERSION)
          name: jx-promote-userservice-prod
      - dir: charts/merchant-service
        steps:
        - sh: jx step changelog --version v\$(cat ../../VERSION)
          name: changelog-merchantservice
        - comment: version the helm chart
          sh: jx step helm version --version \$(cat ../../VERSION)
          name: helm-version-merchantservice
        - comment: release the helm chart
          sh: export CHART_REPOSITORY=https://chartmuseum-jx.juxapp.co.uk && curl -fsSL -o /tmp/helm-v2.17.0-linux-amd64.tar.gz https://get.helm.sh/helm-v2.17.0-linux-amd64.tar.gz && tar -xvzf /tmp/helm-v2.17.0-linux-amd64.tar.gz --strip-components=1 -C /usr/bin/ linux-amd64/helm && helm version --client && helm init --client-only && jx step helm release && helm repo update
          name: helm-release-merchantservice
        - comment: promote to development Environment
          sh: helm init --client-only --stable-repo-url https://charts.helm.sh/stable && jx promote -r jux-jx-charts --verbose --env development --timeout 1h --version \$(cat ../../VERSION)
          name: jx-promote-merchantservice-development
        - comment: promote to production Environment
          sh: helm init --client-only --stable-repo-url https://charts.helm.sh/stable && jx promote -r jux-jx-charts --verbose --no-merge --env prod --timeout 24h --version \$(cat ../../VERSION)
          name: jx-promote-merchantservice-prod

