extends:
  import: classic
  file: maven/pipeline.yaml
pipelines:
  pullRequest:
    build:
      steps:
      - sh: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.15.0/skaffold-linux-amd64 && chmod +x skaffold && cp skaffold /usr/local/bin && /usr/local/bin/skaffold version
        name: skaffold-version
      - sh: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.15.0/skaffold-linux-amd64 && chmod +x skaffold &&  export VERSION=$PREVIEW_VERSION && ./skaffold build -f skaffold.yaml
        name: container-build
    postBuild:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
        name: post-build
    promote:
      steps:
      - dir: charts/preview
        steps:
        - sh: make preview
          name: make-preview
        - sh: jx preview --app $APP_NAME --dir ../..
          name: jx-preview

  release:
    build:
      steps:
      - sh: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.15.0/skaffold-linux-amd64 && chmod +x skaffold && cp skaffold /usr/local/bin && /usr/local/bin/skaffold version
        name: skaffold-version
      - sh: export VERSION=`cat VERSION` && echo "Building with updated skaffold" && curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.15.0/skaffold-linux-amd64 && chmod +x skaffold && pwd && ls -lR charts && ./skaffold build -f skaffold.yaml
        name: container-build
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
        name: post-build
    promote:
      steps:
      - dir: charts/user-service
        steps:
        - sh: jx step changelog --version v\$(cat ../../VERSION)
          name: changelog-userservice
        - comment: version the helm chart
          sh: jx step helm version --version \$(cat ../../VERSION)
          name: helm-version-userservice
        - comment: release the helm chart
          sh: jx step helm release
          name: helm-release-userservice
        - comment: apply the helm chart
          sh: jx step helm install -n user-service -v \$(cat ../../VERSION) jenkins-x-chartmuseum/user-service
          name: helm-install-userservice
        - comment: promote through all 'Auto' promotion Environments
          sh: jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)
          name: jx-promote-userservice
      - dir: charts/merchant-service
        steps:
        - sh: jx step changelog --version v\$(cat ../../VERSION)
          name: changelog-merchantservice
        - comment: version the helm chart
          sh: jx step helm version --version \$(cat ../../VERSION)
          name: helm-version-merchantservice
        - comment: release the helm chart
          sh: jx step helm release
          name: helm-release-merchantservice
        - comment: install the helm chart
          sh: jx step helm install -n merchant-service -v \$(cat ../../VERSION) jenkins-x-chartmuseum/merchant-service
          name: helm-install-merchantservice
        - comment: promote through all 'Auto' promotion Environments
          sh: jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)
          name: jx-promote-merchantservice
